apiVersion: v2
name: ai-pdf-scholar
description: AI Enhanced PDF Scholar - Production-ready Kubernetes deployment
type: application
version: 2.0.0
appVersion: "2.0.0"
keywords:
- ai
- pdf
- rag
- document-processing
- python
- fastapi
- react
home: https://github.com/your-org/ai-enhanced-pdf-scholar
sources:
- https://github.com/your-org/ai-enhanced-pdf-scholar
maintainers:
- name: AI PDF Scholar Team
  email: team@ai-pdf-scholar.com
dependencies:
- name: postgresql
  version: 13.2.24
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
- name: redis
  version: 18.6.1
  repository: https://charts.bitnami.com/bitnami  
  condition: redis.enabled
- name: elasticsearch
  version: 8.5.1
  repository: https://helm.elastic.co
  condition: elasticsearch.enabled
- name: kibana
  version: 8.5.1
  repository: https://helm.elastic.co
  condition: kibana.enabled