{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-pdf-scholar.fullname" . }}-backend
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "ai-pdf-scholar.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
    - name: metrics
      port: {{ .Values.backend.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "ai-pdf-scholar.backend.selectorLabels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-pdf-scholar.fullname" . }}-frontend
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "ai-pdf-scholar.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "ai-pdf-scholar.frontend.selectorLabels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.nginx.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-pdf-scholar.fullname" . }}-nginx
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "ai-pdf-scholar.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
  {{- with .Values.nginx.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - name: http
      port: {{ .Values.nginx.service.port }}
      targetPort: http
      protocol: TCP
    {{- if and .Values.nginx.tls.enabled .Values.nginx.service.httpsPort }}
    - name: https
      port: {{ .Values.nginx.service.httpsPort }}
      targetPort: https
      protocol: TCP
    {{- end }}
  selector:
    {{- include "ai-pdf-scholar.nginx.selectorLabels" . | nindent 4 }}
{{- end }}