apiVersion: v1
kind: Namespace
metadata:
  name: ai-pdf-scholar
  labels:
    name: ai-pdf-scholar
    app.kubernetes.io/name: ai-pdf-scholar
    app.kubernetes.io/part-of: ai-pdf-scholar
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ai-pdf-scholar-quota
  namespace: ai-pdf-scholar
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services: "20"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: ai-pdf-scholar-limits
  namespace: ai-pdf-scholar
spec:
  limits:
  - default:
      cpu: 500m
      memory: 1Gi
    defaultRequest:
      cpu: 100m
      memory: 256Mi
    type: Container
  - default:
      storage: 10Gi
    type: PersistentVolumeClaim