name: "🧹 Pre-commit Checks"

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    name: Run pre-commit
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirements*.txt
            pyproject.toml

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          if [ -f requirements-dev.txt ]; then
            pip install -r requirements-dev.txt
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.17.0'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Install frontend dependencies
        if: hashFiles('frontend/package-lock.json') != ''
        run: |
          cd frontend
          npm ci --prefer-offline --no-audit --no-fund

      - name: Run pre-commit
        run: pre-commit run --all-files --color always --show-diff-on-failure
