name: "🧹 Pre-commit Checks"

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    name: Run pre-commit
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirements*.txt
            pyproject.toml

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          # Install only essential dev tools for fast pre-commit checks
          pip install ruff black isort pytest

      # Skip Node.js setup for faster CI runs - frontend handled separately

      - name: Run pre-commit (essential checks only)
        run: |
          # Skip hooks that modify files and focus on checking only
          SKIP=trailing-whitespace,end-of-file-fixer,black,isort,flake8,bandit,pip-compile,eslint,prettier,markdownlint,detect-secrets,hadolint-docker,yamllint,conventional-pre-commit,frontend-typecheck,check-todos,check-migrations,safety-check,pytest-coverage pre-commit run --all-files --color always
          
          echo "✅ Pre-commit essential checks completed"
